# escape=`

FROM microsoft/windowsservercore
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

# Jacket 9117 
# Radarr 7878 
# Sonarr 8989
# Deluge web 8112
EXPOSE 9117 7878 8989 8112

RUN iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex; `
    choco install -y deluge; `
    choco install --ignore-checksums -y sonarr; `
    choco install -y jackett; `
    choco install -y radarr; `
    Set-Service jackett -startuptype "manual"; `
    Set-Service radarr -startuptype "manual"; `
    Set-Service nzbdrone -startuptype "manual";

VOLUME C:\config
VOLUME C:\deluge_Temp
 
COPY docker-entrypoint.ps1 /

CMD . .\docker-entrypoint.ps1