# escape=`

FROM openjdk:8-windowsservercore
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

EXPOSE 8080 8081 8443 8843 8880


RUN iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex; `
    choco install -y 7zip;

RUN Invoke-WebRequest -Uri 'http://dl.ubnt.com/unifi/5.6.29/UniFi-installer.exe' -Outfile 'C:\UniFi-installer.exe';
   
RUN 7z x C:\UniFi-installer.exe -oC:\app\

VOLUME [ "C:/app/data" ]

COPY docker-entrypoint.ps1 /

CMD . .\docker-entrypoint.ps1